//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PedidosBDEntities : DbContext
    {
        public PedidosBDEntities()
            : base("name=PedidosBDEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public  DbSet<Pedido> Pedidoes { get; set; }
        public  DbSet<PedidoDetalle> PedidoDetalles { get; set; }
        public  DbSet<Producto> Productoes { get; set; }
        public  DbSet<Rol> Rols { get; set; }
        public  DbSet<Usuario> Usuarios { get; set; }
    }
}
